---
extends: default
ignore:
  - .git/
  - vendor/
  - storage/app/scribe/
  - .scribe/
  - node_modules/
rules:
  # 120 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 120
    level: warning
