# Module: php_fpm
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-php_fpm.html

- module: php_fpm
  enabled: true
  metricsets:
    - pool
    - process
  period: 10s
  hosts: ["localhost:80"]
  status_path: "/fpm-status"
  #username: "user"
  #password: "secret"
