name: Publish Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '30 00 * * 6'

jobs:
  push_to_registry:
    name: Push Docker image haakco/ubuntu2004-php80 to Docker Hub
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: haakco/ubuntu2004-php80
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
#          platforms: 'linux/arm64,linux/amd64'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          PHP_VERSION: 8.0
          DOCKER_BUILDKIT: 1
          BASE_UBUNTU_VERSION: 'ubuntu:20.04'
