name: Publish haakco/ubuntu2024-php81 Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '30 00 * * 6'

jobs:
  push_to_registry:
    name: Push Docker image haakco/ubuntu2024-php81 to Docker Hub
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: haakco/ubuntu2024-php81
          tags: |
            type=raw,value={{branch}}-{{sha}}
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_2024_80_X64 }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          build-args:   |
            PHP_VERSION=8.1
            BASE_UBUNTU_VERSION=ubuntu:22.04
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=haakco/ubuntu2024-php81:buildcache-ubuntu2024-php81
          cache-to: type=registry,ref=haakco/ubuntu2024-php81:buildcache-ubuntu2024-php81,mode=max
