---
name: Publish ghcr.io/haakco/ubuntu2404-php84 Docker image
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master
  schedule:
    - cron: '30 22 * * 6'
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build_docker_image:
    uses: ./.github/workflows/template-docker-build.yml
    with:
      DOCKER_FILE: ./docker_build/ubuntuPhp.Dockerfile
      DOCKER_REGISTRY: ghcr.io/haakco
      CREATE_IMAGE_NAME: 'ubuntu2404-php84'
      BASE_IMAGE_NAME: 'ubuntu'
      BASE_IMAGE_VERSION: '24.04'
      PHP_VERSION: '8.4'
      DOCKER_NO_CACHE: ${{ vars.DOCKER_NO_CACHE != 'true' }}
