name: Publish haakco/ubuntu2204-php82 Docker image

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'
    branches:
    - main
    - master
  schedule:
    - cron: '30 22 * * 6'

jobs:
  build_docker_image:
    uses: ./.github/workflows/template-docker-build.yml
    with:
      DOCKER_FILE: 'Dockerfile'
      CREATE_IMAGE_NAME: 'haakco/ubuntu2204-php82'
      BASE_IMAGE_NAME: 'ubuntu'
      BASE_IMAGE_TAG: '22.04'
      PHP_VERSION: '8.2'
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
